# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-11 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('time', models.DateField()),
                ('place', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('state', models.BooleanField()),
                ('tag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='item_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_2', models.CharField(max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('tag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=12)),
                ('tel', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=30)),
                ('tag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='user_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.item')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='id_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.AddField(
            model_name='record',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.item'),
        ),
        migrations.AlterUniqueTogether(
            name='user_item',
            unique_together=set([('item_id',)]),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set([('id_1', 'id_2', 'item_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='item_category',
            unique_together=set([('category_id', 'item_id')]),
        ),
    ]
