# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_1', to='myapp.user'),
        ),
        migrations.AlterField(
            model_name='record',
            name='id_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_2', to='myapp.user'),
        ),
    ]
